#!/usr/bin/env python
# encoding: utf-8

import os.path as p
from landmarkerioserver.api import app_for_mesh_adapter, app_for_image_adapter
from landmarkerioserver.menpoadapter import (MeshMenpoAdapter,
                                             ImageMenpoAdapter)
import webbrowser


def main(mode, asset_dir, landmark_dir=None, template_dir=None,
         cache_dir=False, dev=False):
    r"""

    """
    if mode == 'image':
        adapter = ImageMenpoAdapter(asset_dir,
                                    landmark_dir=landmark_dir,
                                    template_dir=template_dir,
                                    cache_dir=cache_dir)
        app = app_for_image_adapter(adapter, dev=dev)
    elif mode == 'mesh':
        adapter = MeshMenpoAdapter(asset_dir,
                                   landmark_dir=landmark_dir,
                                   template_dir=template_dir,
                                   cache_dir=cache_dir)
        app = app_for_mesh_adapter(adapter, dev=dev)
    else:
        raise ValueError("first argument must be 'image' or 'mesh'")
    if not dev:
        webbrowser.open("http://www.landmarker.io/?mode={}".format(mode))
    app.run()

from landmarkerioserver.menpoadapter import TEMPLATE_DINAME, CACHE_DIRNAME

if __name__ == "__main__":
    from argparse import ArgumentParser
    parser = ArgumentParser(
        description=r"""
        Serve landmarks and assets for landmarker.io through Menpo.
        """)
    parser.add_argument("mode", help="'image' or 'mesh'")
    parser.add_argument("path", help="path that will be searched for assets")
    parser.add_argument("-l", "--landmarks",
                        help="The directory containing the landmarks."
                             "If None provided taken as path/landmarks")
    parser.add_argument("-t", "--templates",
                        help="The directory containing the template files. "
                             "If None provided taken as "
                             "~/{}".format(TEMPLATE_DINAME))
    parser.add_argument("-c", "--cache",
                        help="The directory used to cache assets for serving."
                             "This cache is populated the first time the "
                             "server is run. Subsequent runs verify the cache "
                             "but do not have to rebuild it. Once you have "
                             "finished annotating assets delete this folder "
                             "to reclaim disk space. If None provided taken as"
                             " landmarks/{}".format(CACHE_DIRNAME))
    parser.add_argument("--dev", action='store_true',
                        help="Listen to all CORS requests. Useful for "
                             "development on localhost.")
    ns = parser.parse_args()
    main(ns.mode, ns.path, landmark_dir=ns.landmarks,
         template_dir=ns.templates, cache_dir=ns.cache, dev=ns.dev)
